version: '3'

services:
  golang:
    volumes:
      - ./db:/work
    build:
      context: ./golang
      dockerfile: ./dockerfile
    ports:
      - 80:80
    networks:
      vlan:
        ipv4_address: 192.168.0.1

  python:
    volumes:
      - ./mp3:/work/mp3
    build:
      context: ./python
      dockerfile: ./dockerfile
    ports:
      - 5001:5001
    networks:
      vlan:
        ipv4_address: 192.168.0.2

# networks:
#   vlan:
#     driver: macvlan
#     driver_opts:
#       parent: eth0
#     ipam:
#       config:
#         - subnet: "192.168.0.0/24"
#           ip_range: "192.168.0.64/26"
#           gateway: "192.168.0.1"

networks:
        vlan:
                driver: macvlan
                ipam:
                        driver: default
                        config:
                                - gateway: "192.168.0.254"
                                  subnet: "192.168.0.0/24" 