FROM alpine

RUN apk update
RUN apk add python3 py-pip
RUN pip install --upgrade pip
RUN apk add  --no-cache ffmpeg

WORKDIR /work
COPY . .
RUN pip install -r requirements.txt

EXPOSE 5001

CMD [ "python", "main.py" ]
